apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: infrastructure-alerts
  namespace: prometheus-system
  labels:
    app: prometheus
    release: prometheus
spec:
  groups:
    - name: kubernetes-cluster
      rules:
        - alert: KubernetesNodeDown
          expr: up{job="kubernetes-nodes"} == 0
          for: 5m
          labels:
            severity: critical
            component: infrastructure
          annotations:
            summary: "Kubernetes node is down"
            description: "Node {{ $labels.instance }} has been down for more than 5 minutes"
            runbook_url: "https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubernetesnodedown"

        - alert: KubernetesNodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 10m
          labels:
            severity: warning
            component: infrastructure
          annotations:
            summary: "Kubernetes node not ready"
            description: "Node {{ $labels.node }} has been not ready for more than 10 minutes"

        - alert: KubernetesPodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
          for: 5m
          labels:
            severity: warning
            component: infrastructure
          annotations:
            summary: "Pod is crash looping"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"

        - alert: KubernetesPodNotReady
          expr: kube_pod_status_phase{phase=~"Pending|Unknown"} > 0
          for: 10m
          labels:
            severity: warning
            component: infrastructure
          annotations:
            summary: "Pod not ready"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been not ready for more than 10 minutes"

    - name: kubernetes-resources
      rules:
        - alert: KubernetesNodeHighCPU
          expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
          for: 5m
          labels:
            severity: warning
            component: infrastructure
          annotations:
            summary: "High CPU usage on node"
            description: "Node {{ $labels.instance }} has high CPU usage: {{ $value }}%"

        - alert: KubernetesNodeHighMemory
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
          for: 5m
          labels:
            severity: warning
            component: infrastructure
          annotations:
            summary: "High memory usage on node"
            description: "Node {{ $labels.instance }} has high memory usage: {{ $value }}%"

        - alert: KubernetesNodeDiskSpaceLow
          expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 85
          for: 5m
          labels:
            severity: warning
            component: infrastructure
          annotations:
            summary: "Low disk space on node"
            description: "Node {{ $labels.instance }} has low disk space on {{ $labels.mountpoint }}: {{ $value }}%"

    - name: certificate-management
      rules:
        - alert: CertificateExpiringSoon
          expr: (x509_cert_not_after - time()) / 86400 < 30
          for: 1h
          labels:
            severity: warning
            component: security
          annotations:
            summary: "Certificate expiring soon"
            description: "Certificate {{ $labels.subject_CN }} will expire in {{ $value }} days"

        - alert: CertificateExpired
          expr: (x509_cert_not_after - time()) / 86400 < 0
          for: 1m
          labels:
            severity: critical
            component: security
          annotations:
            summary: "Certificate expired"
            description: "Certificate {{ $labels.subject_CN }} has expired"
