apiVersion: v1
kind: Service
metadata:
  name: frontend-metrics
  namespace: banv-projects
  labels:
    app: frontend
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: frontend
  ports:
    - name: metrics
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  namespace: banv-projects
  labels:
    app: backend
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: backend
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
      protocol: TCP
