apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mindxacrbanv.azurecr.io/banv-projects-backend:v1.5.0
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: FRONTEND_URL
              value: "https://banv-app-dev.mindx.edu.vn"
            - name: SESSION_SECRET
              value: "your-session-secret"
            - name: OAUTH_CLIENT_ID
              value: "banv-aks"
            - name: OAUTH_CLIENT_SECRET
              value: "8daaa53ae9256b929f2b5a2ac04ce66375ed2f92ac"
            - name: OAUTH_CALLBACK_URL
              value: "https://banv-api-dev.mindx.edu.vn/oauth/openid/callback"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: banv-projects
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
