apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-plugin
  namespace: mindx-projects
  annotations:
    kubernetes.io/ingress.class: kong
plugin: key-auth
config:
  key_names:
    - apikey
    - x-api-key
  hide_credentials: true
  key_in_header: true
  key_in_query: false
  key_in_body: false
  run_on_preflight: true
  anonymous: "api-user" # Open comment to allow access without api key
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin
  namespace: mindx-projects
  annotations:
    kubernetes.io/ingress.class: kong
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - apikey
    - x-api-key
    - X-Anonymous-User
    - X-Request-Type
  exposed_headers:
    - X-Auth-Token
    - X-User-Type
    - X-User-ID
  credentials: true
  max_age: 3600
  preflight_continue: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-plugin
  namespace: mindx-projects
  annotations:
    kubernetes.io/ingress.class: kong
plugin: rate-limiting
config:
  minute: 100
  hour: 1000
  policy: local
