apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring-insights
  annotations:
    config.kubernetes.io/local-config: "true"

# Reference to subfolder kustomizations
resources:
  - azure-monitor-setup/
  - prometheus-setup/
  - alert-setup/

commonLabels:
  monitoring.mindx.edu.vn/component: insights
  app.kubernetes.io/part-of: monitoring-stack

namespace: banv-projects
