apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
  namespace: banv-projects
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: banv@mindx.edu.vn
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-dev
    # Add a single challenge solver, HTTP01 will be used
    solvers:
      - http01:
          ingress:
            class: kong
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: banv-projects
spec:
  acme:
    # The ACME server URL for staging (use this for testing)
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: banv@mindx.edu.vn
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Add a single challenge solver, HTTP01 will be used
    solvers:
      - http01:
          ingress:
            class: kong
