# Key Auth Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-plugin
  namespace: banv-projects
  annotations:
    kubernetes.io/ingress.class: kong
plugin: key-auth
config:
  key_names:
    - apikey
    - x-api-key
  hide_credentials: true
  key_in_header: true
  key_in_query: false
  key_in_body: false
  run_on_preflight: true
  anonymous: "api-user" # Open comment to allow access without api key
---
# Cors Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin
  namespace: banv-projects
  annotations:
    kubernetes.io/ingress.class: kong
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - apikey
    - x-api-key
    - X-Anonymous-User
    - X-Request-Type
  exposed_headers:
    - X-Auth-Token
    - X-User-Type
    - X-User-ID
  credentials: true
  max_age: 3600
  preflight_continue: false
---
# Rate Limiting Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-plugin
  namespace: banv-projects
  annotations:
    kubernetes.io/ingress.class: kong
plugin: rate-limiting
config:
  minute: 100
  hour: 1000
  policy: local
---
# OAuth2 Plugin for OpenID Connect SSO
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oauth2-plugin
  namespace: banv-projects
  annotations:
    kubernetes.io/ingress.class: kong
plugin: oauth2
config:
  scopes:
    - openid
    - profile
    - email
  mandatory_scope: true
  enable_authorization_code: true
  enable_client_credentials: false
  enable_implicit_grant: false
  enable_password_grant: false
  token_expiration: 7200
  refresh_token_ttl: 1209600
  provision_key: "mindx-oauth-provision-key"
  global_credentials: false
  auth_header_name: "Authorization"
  hide_credentials: false
  anonymous: null
