apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banv-projects

resources:
  - cluster-issuer.yaml
  - kong-ingress.yaml
  - kong-ingress-plugin.yaml
  - kong-ingress-consumer.yaml
